### ISSUE TITLE
Impfzentrum Mannheim Maimarkthalle hinzufügen

### ISSUE THREAD

**Issue by LX2305** [kyi87/ImpfTerminBot#1]
Es wäre super wenn noch weitere Impfzentren hinzugefügt werden könnten, z.B. Mannheim Maimarkthalle.

außerdem vielleicht einen Testbutton für den Notification Sound

**Comment by kyi87** [comment]
Das Impfzentrum kam anscheinend neu hinzu. Kleiner Workaround bis ich die Version neu erstellt habe: 
Die aktualisierte Datei data.json im Installationsverzeichnis ersetzen:
https://github.com/kyi87/ImpfTerminBot/blob/master/ImpfTerminBot.GUI/data.json

**Comment by LX2305** [comment]
So schnell habe ich damit nicht gerechnet :D Super danke!!
