### ISSUE TITLE
Fehlermeldung nach Starten des Tools

### ISSUE THREAD

**Issue by webber1234** [kyi87/ImpfTerminBot#2]
**Describe the bug**
Nach dem eingeben von Vermittlungscode, Bundesland und Impfzentrum öffnet sich das Terminal und der Chrome-Borwser. Im Terminal erscheint die Meldung 
"[20320:18328:0504/161552.770:ERROR:device_event_log_impl.cc(214)] [16:15:52.769] USB: usb_device_handle_win.cc:1054 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
[20320:18328:0504/161552.777:ERROR:device_event_log_impl.cc(214)] [16:15:52.776] USB: usb_device_handle_win.cc:1054 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)"

Danach kommt eine Fehlermeldung.

Gibt es hier einen Fix?

Windows 10 Home, 19042.928

**Comment by webber1234** [comment]
Hi, anbei ein Screenshot von der gesamten Prozedur. Alle unrelevanten USB-Geräte sind entfernt.
Was ebenfalls auffällt: Der Chrome kommt automatisch in den Warteraum, bei einem anderen Browser passiert das beim gleichen Zentrum nicht. Hast du eine Idee?
![Unbenannt](https://user-images.githubusercontent.com/83654966/117057248-84498680-ad1d-11eb-84b7-933aa945eda6.JPG)

**Comment by webber1234** [comment]
Nach einiger Zeit kommt diese Meldung
![Unbenannt](https://user-images.githubusercontent.com/83654966/117060126-df30ad00-ad20-11eb-840f-c6cb591413ff.JPG)

**Comment by kyi87** [comment]
Das mit dem Warteraum sollte kein Problem sein, das Programm wartet solange, bis die Wartezeit vorbei ist. Wenn du direkt über den Browser reingehst wird möglicherweise eine andere Server-Nummer gewählt. In der nächsten Version kann man die Server-Nummer und den Browser einstellen. Vielleicht probierst du das ganze nochmals mir Firefox dann.

Zur Fehlermeldung: Ich glaube der Fehler im Terminal macht erstmal kein problem. Schließt du entweder Terminal oder Browser? Weil dann kann so eine Fehlermeldung kommen.
